# docker-compose version
version: '3.8'

services:
  # Container for OpenAI Flask app
  openai:
    # Default image
    image: openai:1.0
    # Where to build from if no image available
    build: 
      dockerfile: Dockerfile
    # Set env variables
    environment:
      - OPENAI_API_KEY=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
    # Map ports
    ports:
      - 5000:5000